---
- name: Testing andrewrothstein.zookeeper
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'zkServer.sh version'
      ansible.builtin.command: bash -l -c 'zkServer.sh version'
      changed_when: false
      register: zookeeper_test_output
    - name: Output from 'zkServer.sh version'
      ansible.builtin.debug:
        msg: '{{ zookeeper_test_output.stdout }}'
